### ISSUE TITLE
Service backend needs to be port 80?

### ISSUE THREAD

**Issue by wstrange** [cloudflare/cloudflare-warp-ingress#5]
I had a service defined with a backend port of 7744.  (targetPort: 7744 and port: 7744).

The nginx ingress deals with this OK - and routes the front end ingress (80/443) to the right destination port. 

The warp ingress controller seems to assume the service will be on port 80.

**Comment by ntfrnzn** [comment]
Definitely a failure in testing 👎.  Will fix soon.

**Comment by ntfrnzn** [comment]
built as image quay.io/stackpoint/warp-controller:v0.3.1
